name: CL
on:
  push:
    branches:
      - main
   
jobs:
  CL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Run Isreal
        run: python main.py
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          LESSONS: 10
